version: "3"

services:
  gumbot:
    build:
      context: ./
      dockerfile: Dockerfile
    image: bradcornford/discord-gumbot:latest
    container_name: gumbot
    working_dir: /usr/src/app
    environment:
      TZ: "Europe/London"
    env_file:
      - .env
